
name: 'kp_analysis'
version: '1.0.0'

profile: 'kp_analysis'

model-paths: ["models"]

models:
  kp_analysis:
    staging:
      +materialized: table
      cms:
        +schema: staging
      bls:
        +schema: staging
      covered_ca:
        +schema: staging
      census:
        +schema: staging
